Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5601, host: 5601
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.provision "file", source: "elasticsearch", destination: "/home/vagrant"
  config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
        echo "export INSTAGRAM_LOGIN='******'" >> /etc/profile.d/insta.sh
        echo "export INSTAGRAM_PASSWORD='******'" >> /etc/profile.d/insta.sh
        echo "export BATCH_COUNT='100'" >> /etc/profile.d/insta.sh
        echo "export BATCH_INTERVAL='3000'" >> /etc/profile.d/insta.sh
  SHELL
end
